/**
 * SmartRoute Maharashtra - Static Demo Dataset
 * All data is SAMPLE / DEMO data for college DSA project demonstration.
 * Not real-time. Architecture supports future API integration.
 */

const STATIONS = [
  // Core Pune
  { id: "prs", name: "Pune Railway Station", area: "Pune", lat: 18.5289, lng: 73.8744, type: "major" },
  { id: "shiv", name: "Shivajinagar", area: "Pune", lat: 18.5314, lng: 73.8446, type: "major" },
  { id: "swar", name: "Swargate", area: "Pune", lat: 18.5018, lng: 73.8636, type: "major" },
  { id: "decc", name: "Deccan", area: "Pune", lat: 18.5167, lng: 73.8417, type: "major" },
  { id: "koth", name: "Kothrud", area: "Pune", lat: 18.5074, lng: 73.8077, type: "hub" },
  { id: "hada", name: "Hadapsar", area: "Pune", lat: 18.5089, lng: 73.9260, type: "hub" },
  { id: "katr", name: "Katraj", area: "Pune", lat: 18.4575, lng: 73.8678, type: "hub" },
  { id: "bane", name: "Baner", area: "Pune", lat: 18.5590, lng: 73.7868, type: "hub" },
  { id: "aund", name: "Aundh", area: "Pune", lat: 18.5580, lng: 73.8070, type: "hub" },
  { id: "waka", name: "Wakad", area: "Pune", lat: 18.5990, lng: 73.7630, type: "hub" },
  { id: "hinj", name: "Hinjawadi", area: "Pune", lat: 18.5912, lng: 73.7389, type: "hub" },
  { id: "pimp", name: "Pimpri", area: "PCMC", lat: 18.6298, lng: 73.7997, type: "hub" },
  { id: "chin", name: "Chinchwad", area: "PCMC", lat: 18.6292, lng: 73.7991, type: "hub" },
  { id: "akur", name: "Akurdi", area: "PCMC", lat: 18.6480, lng: 73.7780, type: "hub" },
  { id: "nigd", name: "Nigdi", area: "PCMC", lat: 18.6620, lng: 73.7700, type: "hub" },
  { id: "pcmc", name: "PCMC", area: "PCMC", lat: 18.6290, lng: 73.8130, type: "major" },
  { id: "civi", name: "Civil Court", area: "Pune", lat: 18.5204, lng: 73.8567, type: "metro" },
  { id: "vana", name: "Vanaz", area: "Pune", lat: 18.5070, lng: 73.8200, type: "metro" },
  { id: "ramw", name: "Ramwadi", area: "Pune", lat: 18.5520, lng: 73.9200, type: "metro" },
  { id: "bund", name: "Bund Garden", area: "Pune", lat: 18.5340, lng: 73.8770, type: "hub" },
  { id: "yera", name: "Yerawada", area: "Pune", lat: 18.5520, lng: 73.8900, type: "hub" },
  { id: "khar", name: "Kharadi", area: "Pune", lat: 18.5510, lng: 73.9400, type: "hub" },
  { id: "vima", name: "Viman Nagar", area: "Pune", lat: 18.5679, lng: 73.9143, type: "hub" },
  { id: "airp", name: "Pune Airport", area: "Pune", lat: 18.5822, lng: 73.9197, type: "major" },
  { id: "bhos", name: "Bhosari", area: "PCMC", lat: 18.6300, lng: 73.8450, type: "hub" },
  { id: "dapo", name: "Dapodi", area: "PCMC", lat: 18.5850, lng: 73.8300, type: "hub" },
  { id: "khad", name: "Khadki", area: "Pune", lat: 18.5630, lng: 73.8520, type: "hub" },
  { id: "warj", name: "Warje", area: "Pune", lat: 18.4860, lng: 73.8000, type: "hub" },
  { id: "dhay", name: "Dhayari", area: "Pune", lat: 18.4500, lng: 73.8100, type: "hub" },
  { id: "sinh", name: "Sinhagad Road", area: "Pune", lat: 18.4600, lng: 73.8200, type: "hub" },
  { id: "vitp", name: "VIT Pune", area: "Pune", lat: 18.4635, lng: 73.8682, type: "landmark" },
  { id: "camp", name: "Camp", area: "Pune", lat: 18.5190, lng: 73.8770, type: "hub" },
  { id: "fcro", name: "FC Road", area: "Pune", lat: 18.5200, lng: 73.8400, type: "hub" },
  { id: "jmro", name: "JM Road", area: "Pune", lat: 18.5150, lng: 73.8400, type: "hub" },
  { id: "kore", name: "Koregaon Park", area: "Pune", lat: 18.5362, lng: 73.8937, type: "hub" },
  { id: "maga", name: "Magarpatta", area: "Pune", lat: 18.5150, lng: 73.9300, type: "hub" },
  { id: "phoe", name: "Phoenix Mall", area: "Pune", lat: 18.5600, lng: 73.9100, type: "landmark" },
  { id: "balewadi", name: "Balewadi", area: "Pune", lat: 18.5800, lng: 73.7700, type: "hub" },
  { id: "bavd", name: "Bavdhan", area: "Pune", lat: 18.5150, lng: 73.7800, type: "hub" },
  { id: "sus", name: "Sus", area: "Pune", lat: 18.5500, lng: 73.7500, type: "hub" },
  { id: "chakan", name: "Chakan", area: "Pune", lat: 18.7600, lng: 73.8600, type: "hub" },
  { id: "talegaon", name: "Talegaon", area: "Pune", lat: 18.7350, lng: 73.6750, type: "hub" },
  // Metro stations
  { id: "anand", name: "Anand Nagar", area: "Pune", lat: 18.5000, lng: 73.8300, type: "metro" },
  { id: "ideal", name: "Ideal Colony", area: "Pune", lat: 18.5100, lng: 73.8350, type: "metro" },
  { id: "nals", name: "Nal Stop", area: "Pune", lat: 18.5120, lng: 73.8380, type: "metro" },
  { id: "garw", name: "Garware College", area: "Pune", lat: 18.5140, lng: 73.8400, type: "metro" },
  { id: "samb", name: "Sambhaji Park", area: "Pune", lat: 18.5180, lng: 73.8450, type: "metro" },
  { id: "pmc", name: "PMC Building", area: "Pune", lat: 18.5200, lng: 73.8500, type: "metro" },
  { id: "mang", name: "Mangalwar Peth", area: "Pune", lat: 18.5150, lng: 73.8600, type: "metro" },
  { id: "puneuni", name: "Pune University", area: "Pune", lat: 18.5500, lng: 73.8250, type: "hub" }
];

/**
 * Connections: directed edges for multimodal graph
 * mode: Bus | Metro | Auto | Train | Taxi | Walking | Bicycle
 * All values are ESTIMATED / SAMPLE for demo purposes.
 */
const CONNECTIONS = [
  // Bus routes - major corridors
  { id: "c1", source: "prs", destination: "shiv", mode: "Bus", distance: 3.5, time: 15, fare: 15, routeNumber: "PMT-101", stops: ["Pune Railway Station", "Bund Garden", "Shivajinagar"] },
  { id: "c2", source: "shiv", destination: "prs", mode: "Bus", distance: 3.5, time: 15, fare: 15, routeNumber: "PMT-101", stops: ["Shivajinagar", "Bund Garden", "Pune Railway Station"] },
  { id: "c3", source: "prs", destination: "swar", mode: "Bus", distance: 5.2, time: 22, fare: 18, routeNumber: "PMT-5", stops: ["Pune Railway Station", "Camp", "Swargate"] },
  { id: "c4", source: "swar", destination: "prs", mode: "Bus", distance: 5.2, time: 22, fare: 18, routeNumber: "PMT-5", stops: ["Swargate", "Camp", "Pune Railway Station"] },
  { id: "c5", source: "swar", destination: "katr", mode: "Bus", distance: 6.2, time: 25, fare: 20, routeNumber: "PMT-12", stops: ["Swargate", "Dhankawadi", "Katraj"] },
  { id: "c6", source: "katr", destination: "swar", mode: "Bus", distance: 6.2, time: 25, fare: 20, routeNumber: "PMT-12", stops: ["Katraj", "Dhankawadi", "Swargate"] },
  { id: "c7", source: "katr", destination: "vitp", mode: "Bus", distance: 4.5, time: 18, fare: 15, routeNumber: "PMT-VIT", stops: ["Katraj", "Kondhwa", "VIT Pune"] },
  { id: "c8", source: "vitp", destination: "katr", mode: "Bus", distance: 4.5, time: 18, fare: 15, routeNumber: "PMT-VIT", stops: ["VIT Pune", "Kondhwa", "Katraj"] },
  { id: "c9", source: "swar", destination: "vitp", mode: "Bus", distance: 8.0, time: 30, fare: 22, routeNumber: "PMT-30", stops: ["Swargate", "Bibwewadi", "VIT Pune"] },
  { id: "c10", source: "vitp", destination: "swar", mode: "Bus", distance: 8.0, time: 30, fare: 22, routeNumber: "PMT-30", stops: ["VIT Pune", "Bibwewadi", "Swargate"] },
  { id: "c11", source: "shiv", destination: "civi", mode: "Bus", distance: 2.0, time: 10, fare: 10, routeNumber: "PMT-20", stops: ["Shivajinagar", "FC Road", "Civil Court"] },
  { id: "c12", source: "civi", destination: "shiv", mode: "Bus", distance: 2.0, time: 10, fare: 10, routeNumber: "PMT-20", stops: ["Civil Court", "FC Road", "Shivajinagar"] },
  { id: "c13", source: "civi", destination: "vitp", mode: "Bus", distance: 5.5, time: 20, fare: 15, routeNumber: "PMT-45", stops: ["Civil Court", "Swargate", "VIT Pune"] },
  { id: "c14", source: "vitp", destination: "civi", mode: "Bus", distance: 5.5, time: 20, fare: 15, routeNumber: "PMT-45", stops: ["VIT Pune", "Swargate", "Civil Court"] },
  { id: "c15", source: "prs", destination: "civi", mode: "Bus", distance: 4.0, time: 18, fare: 15, routeNumber: "PMT-7", stops: ["Pune Railway Station", "Camp", "Civil Court"] },
  { id: "c16", source: "civi", destination: "prs", mode: "Bus", distance: 4.0, time: 18, fare: 15, routeNumber: "PMT-7", stops: ["Civil Court", "Camp", "Pune Railway Station"] },
  { id: "c17", source: "decc", destination: "koth", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-55", stops: ["Deccan", "Karve Road", "Kothrud"] },
  { id: "c18", source: "koth", destination: "decc", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-55", stops: ["Kothrud", "Karve Road", "Deccan"] },
  { id: "c19", source: "swar", destination: "hada", mode: "Bus", distance: 9.0, time: 35, fare: 25, routeNumber: "PMT-90", stops: ["Swargate", "Hadapsar"] },
  { id: "c20", source: "hada", destination: "swar", mode: "Bus", distance: 9.0, time: 35, fare: 25, routeNumber: "PMT-90", stops: ["Hadapsar", "Swargate"] },
  { id: "c21", source: "prs", destination: "vima", mode: "Bus", distance: 12.0, time: 40, fare: 30, routeNumber: "PMT-Airport", stops: ["Pune Railway Station", "Yerawada", "Viman Nagar"] },
  { id: "c22", source: "vima", destination: "prs", mode: "Bus", distance: 12.0, time: 40, fare: 30, routeNumber: "PMT-Airport", stops: ["Viman Nagar", "Yerawada", "Pune Railway Station"] },
  { id: "c23", source: "vima", destination: "airp", mode: "Bus", distance: 4.5, time: 15, fare: 20, routeNumber: "PMT-AP", stops: ["Viman Nagar", "Airport"] },
  { id: "c24", source: "airp", destination: "vima", mode: "Bus", distance: 4.5, time: 15, fare: 20, routeNumber: "PMT-AP", stops: ["Airport", "Viman Nagar"] },
  { id: "c25", source: "shiv", destination: "aund", mode: "Bus", distance: 6.0, time: 25, fare: 18, routeNumber: "PMT-A1", stops: ["Shivajinagar", "Aundh"] },
  { id: "c26", source: "aund", destination: "shiv", mode: "Bus", distance: 6.0, time: 25, fare: 18, routeNumber: "PMT-A1", stops: ["Aundh", "Shivajinagar"] },
  { id: "c27", source: "aund", destination: "waka", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-W1", stops: ["Aundh", "Wakad"] },
  { id: "c28", source: "waka", destination: "aund", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-W1", stops: ["Wakad", "Aundh"] },
  { id: "c29", source: "waka", destination: "hinj", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-H1", stops: ["Wakad", "Hinjawadi"] },
  { id: "c30", source: "hinj", destination: "waka", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-H1", stops: ["Hinjawadi", "Wakad"] },
  { id: "c31", source: "pimp", destination: "chin", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMPML-1", stops: ["Pimpri", "Chinchwad"] },
  { id: "c32", source: "chin", destination: "pimp", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMPML-1", stops: ["Chinchwad", "Pimpri"] },
  { id: "c33", source: "chin", destination: "akur", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMPML-2", stops: ["Chinchwad", "Akurdi"] },
  { id: "c34", source: "akur", destination: "chin", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMPML-2", stops: ["Akurdi", "Chinchwad"] },
  { id: "c35", source: "akur", destination: "nigd", mode: "Bus", distance: 2.0, time: 8, fare: 8, routeNumber: "PMPML-3", stops: ["Akurdi", "Nigdi"] },
  { id: "c36", source: "nigd", destination: "akur", mode: "Bus", distance: 2.0, time: 8, fare: 8, routeNumber: "PMPML-3", stops: ["Nigdi", "Akurdi"] },
  { id: "c37", source: "pcmc", destination: "pimp", mode: "Bus", distance: 3.5, time: 15, fare: 12, routeNumber: "PMPML-PC", stops: ["PCMC", "Pimpri"] },
  { id: "c38", source: "pimp", destination: "pcmc", mode: "Bus", distance: 3.5, time: 15, fare: 12, routeNumber: "PMPML-PC", stops: ["Pimpri", "PCMC"] },
  { id: "c39", source: "shiv", destination: "pcmc", mode: "Bus", distance: 12.0, time: 40, fare: 25, routeNumber: "PMT-PCMC", stops: ["Shivajinagar", "Dapodi", "PCMC"] },
  { id: "c40", source: "pcmc", destination: "shiv", mode: "Bus", distance: 12.0, time: 40, fare: 25, routeNumber: "PMT-PCMC", stops: ["PCMC", "Dapodi", "Shivajinagar"] },
  { id: "c41", source: "koth", destination: "warj", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-K1", stops: ["Kothrud", "Warje"] },
  { id: "c42", source: "warj", destination: "koth", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-K1", stops: ["Warje", "Kothrud"] },
  { id: "c43", source: "katr", destination: "dhay", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-D1", stops: ["Katraj", "Dhayari"] },
  { id: "c44", source: "dhay", destination: "katr", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-D1", stops: ["Dhayari", "Katraj"] },
  { id: "c45", source: "hada", destination: "khar", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-KH", stops: ["Hadapsar", "Kharadi"] },
  { id: "c46", source: "khar", destination: "hada", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-KH", stops: ["Kharadi", "Hadapsar"] },
  { id: "c47", source: "khar", destination: "vima", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-KV", stops: ["Kharadi", "Viman Nagar"] },
  { id: "c48", source: "vima", destination: "khar", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMT-KV", stops: ["Viman Nagar", "Kharadi"] },
  { id: "c49", source: "bane", destination: "balewadi", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-B1", stops: ["Baner", "Balewadi"] },
  { id: "c50", source: "balewadi", destination: "bane", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-B1", stops: ["Balewadi", "Baner"] },

  // Metro - Purple Line (Aqua/Purple approximated)
  { id: "m1", source: "vana", destination: "anand", mode: "Metro", distance: 1.8, time: 4, fare: 10, routeNumber: "Purple Line", stops: ["Vanaz", "Anand Nagar"] },
  { id: "m2", source: "anand", destination: "vana", mode: "Metro", distance: 1.8, time: 4, fare: 10, routeNumber: "Purple Line", stops: ["Anand Nagar", "Vanaz"] },
  { id: "m3", source: "anand", destination: "ideal", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Anand Nagar", "Ideal Colony"] },
  { id: "m4", source: "ideal", destination: "anand", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Ideal Colony", "Anand Nagar"] },
  { id: "m5", source: "ideal", destination: "nals", mode: "Metro", distance: 1.2, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Ideal Colony", "Nal Stop"] },
  { id: "m6", source: "nals", destination: "ideal", mode: "Metro", distance: 1.2, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Nal Stop", "Ideal Colony"] },
  { id: "m7", source: "nals", destination: "garw", mode: "Metro", distance: 1.0, time: 2, fare: 10, routeNumber: "Purple Line", stops: ["Nal Stop", "Garware College"] },
  { id: "m8", source: "garw", destination: "nals", mode: "Metro", distance: 1.0, time: 2, fare: 10, routeNumber: "Purple Line", stops: ["Garware College", "Nal Stop"] },
  { id: "m9", source: "garw", destination: "decc", mode: "Metro", distance: 1.3, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Garware College", "Deccan Gymkhana"] },
  { id: "m10", source: "decc", destination: "garw", mode: "Metro", distance: 1.3, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Deccan Gymkhana", "Garware College"] },
  { id: "m11", source: "decc", destination: "samb", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Deccan Gymkhana", "Sambhaji Park"] },
  { id: "m12", source: "samb", destination: "decc", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Sambhaji Park", "Deccan Gymkhana"] },
  { id: "m13", source: "samb", destination: "pmc", mode: "Metro", distance: 1.2, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Sambhaji Park", "PMC Building"] },
  { id: "m14", source: "pmc", destination: "samb", mode: "Metro", distance: 1.2, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["PMC Building", "Sambhaji Park"] },
  { id: "m15", source: "pmc", destination: "civi", mode: "Metro", distance: 1.0, time: 2, fare: 10, routeNumber: "Purple Line", stops: ["PMC Building", "Civil Court"] },
  { id: "m16", source: "civi", destination: "pmc", mode: "Metro", distance: 1.0, time: 2, fare: 10, routeNumber: "Purple Line", stops: ["Civil Court", "PMC Building"] },
  { id: "m17", source: "civi", destination: "mang", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Civil Court", "Mangalwar Peth"] },
  { id: "m18", source: "mang", destination: "civi", mode: "Metro", distance: 1.5, time: 3, fare: 10, routeNumber: "Purple Line", stops: ["Mangalwar Peth", "Civil Court"] },
  { id: "m19", source: "mang", destination: "prs", mode: "Metro", distance: 2.0, time: 5, fare: 15, routeNumber: "Purple Line", stops: ["Mangalwar Peth", "Pune Railway Station"] },
  { id: "m20", source: "prs", destination: "mang", mode: "Metro", distance: 2.0, time: 5, fare: 15, routeNumber: "Purple Line", stops: ["Pune Railway Station", "Mangalwar Peth"] },
  // Aqua Line approximation (Ramwadi - Vanaz direction via Civil)
  { id: "m21", source: "ramw", destination: "khar", mode: "Metro", distance: 3.0, time: 7, fare: 15, routeNumber: "Aqua Line", stops: ["Ramwadi", "Kharadi"] },
  { id: "m22", source: "khar", destination: "ramw", mode: "Metro", distance: 3.0, time: 7, fare: 15, routeNumber: "Aqua Line", stops: ["Kharadi", "Ramwadi"] },
  { id: "m23", source: "ramw", destination: "yera", mode: "Metro", distance: 2.5, time: 6, fare: 12, routeNumber: "Aqua Line", stops: ["Ramwadi", "Yerawada"] },
  { id: "m24", source: "yera", destination: "ramw", mode: "Metro", distance: 2.5, time: 6, fare: 12, routeNumber: "Aqua Line", stops: ["Yerawada", "Ramwadi"] },
  { id: "m25", source: "yera", destination: "bund", mode: "Metro", distance: 2.0, time: 5, fare: 10, routeNumber: "Aqua Line", stops: ["Yerawada", "Bund Garden"] },
  { id: "m26", source: "bund", destination: "yera", mode: "Metro", distance: 2.0, time: 5, fare: 10, routeNumber: "Aqua Line", stops: ["Bund Garden", "Yerawada"] },
  { id: "m27", source: "bund", destination: "civi", mode: "Metro", distance: 2.5, time: 6, fare: 12, routeNumber: "Aqua Line", stops: ["Bund Garden", "Civil Court"] },
  { id: "m28", source: "civi", destination: "bund", mode: "Metro", distance: 2.5, time: 6, fare: 12, routeNumber: "Aqua Line", stops: ["Civil Court", "Bund Garden"] },

  // Auto Rickshaw (estimated fares - sample)
  { id: "a1", source: "katr", destination: "swar", mode: "Auto", distance: 6.2, time: 20, fare: 90, routeNumber: "Auto", stops: [] },
  { id: "a2", source: "swar", destination: "katr", mode: "Auto", distance: 6.2, time: 20, fare: 90, routeNumber: "Auto", stops: [] },
  { id: "a3", source: "prs", destination: "shiv", mode: "Auto", distance: 3.5, time: 12, fare: 60, routeNumber: "Auto", stops: [] },
  { id: "a4", source: "shiv", destination: "prs", mode: "Auto", distance: 3.5, time: 12, fare: 60, routeNumber: "Auto", stops: [] },
  { id: "a5", source: "civi", destination: "vitp", mode: "Auto", distance: 5.5, time: 18, fare: 80, routeNumber: "Auto", stops: [] },
  { id: "a6", source: "vitp", destination: "civi", mode: "Auto", distance: 5.5, time: 18, fare: 80, routeNumber: "Auto", stops: [] },
  { id: "a7", source: "swar", destination: "vitp", mode: "Auto", distance: 8.0, time: 25, fare: 110, routeNumber: "Auto", stops: [] },
  { id: "a8", source: "vitp", destination: "swar", mode: "Auto", distance: 8.0, time: 25, fare: 110, routeNumber: "Auto", stops: [] },
  { id: "a9", source: "shiv", destination: "civi", mode: "Auto", distance: 2.0, time: 8, fare: 40, routeNumber: "Auto", stops: [] },
  { id: "a10", source: "civi", destination: "shiv", mode: "Auto", distance: 2.0, time: 8, fare: 40, routeNumber: "Auto", stops: [] },
  { id: "a11", source: "prs", destination: "civi", mode: "Auto", distance: 4.0, time: 15, fare: 70, routeNumber: "Auto", stops: [] },
  { id: "a12", source: "civi", destination: "prs", mode: "Auto", distance: 4.0, time: 15, fare: 70, routeNumber: "Auto", stops: [] },
  { id: "a13", source: "decc", destination: "koth", mode: "Auto", distance: 3.0, time: 10, fare: 50, routeNumber: "Auto", stops: [] },
  { id: "a14", source: "koth", destination: "decc", mode: "Auto", distance: 3.0, time: 10, fare: 50, routeNumber: "Auto", stops: [] },
  { id: "a15", source: "waka", destination: "hinj", mode: "Auto", distance: 4.0, time: 12, fare: 60, routeNumber: "Auto", stops: [] },
  { id: "a16", source: "hinj", destination: "waka", mode: "Auto", distance: 4.0, time: 12, fare: 60, routeNumber: "Auto", stops: [] },
  { id: "a17", source: "vima", destination: "airp", mode: "Auto", distance: 4.5, time: 12, fare: 70, routeNumber: "Auto", stops: [] },
  { id: "a18", source: "airp", destination: "vima", mode: "Auto", distance: 4.5, time: 12, fare: 70, routeNumber: "Auto", stops: [] },

  // Local Train / Regional
  { id: "t1", source: "prs", destination: "pimp", mode: "Train", distance: 15.0, time: 25, fare: 10, routeNumber: "Local-Pune-Lonavala", stops: ["Pune Railway Station", "Shivajinagar", "Khadki", "Dapodi", "Pimpri"] },
  { id: "t2", source: "pimp", destination: "prs", mode: "Train", distance: 15.0, time: 25, fare: 10, routeNumber: "Local-Pune-Lonavala", stops: ["Pimpri", "Dapodi", "Khadki", "Shivajinagar", "Pune Railway Station"] },
  { id: "t3", source: "pimp", destination: "chin", mode: "Train", distance: 3.0, time: 6, fare: 5, routeNumber: "Local", stops: ["Pimpri", "Chinchwad"] },
  { id: "t4", source: "chin", destination: "pimp", mode: "Train", distance: 3.0, time: 6, fare: 5, routeNumber: "Local", stops: ["Chinchwad", "Pimpri"] },
  { id: "t5", source: "chin", destination: "akur", mode: "Train", distance: 4.0, time: 8, fare: 5, routeNumber: "Local", stops: ["Chinchwad", "Akurdi"] },
  { id: "t6", source: "akur", destination: "chin", mode: "Train", distance: 4.0, time: 8, fare: 5, routeNumber: "Local", stops: ["Akurdi", "Chinchwad"] },
  { id: "t7", source: "akur", destination: "nigd", mode: "Train", distance: 3.0, time: 6, fare: 5, routeNumber: "Local", stops: ["Akurdi", "Nigdi"] },
  { id: "t8", source: "nigd", destination: "akur", mode: "Train", distance: 3.0, time: 6, fare: 5, routeNumber: "Local", stops: ["Nigdi", "Akurdi"] },
  { id: "t9", source: "prs", destination: "khad", mode: "Train", distance: 6.0, time: 12, fare: 8, routeNumber: "Local", stops: ["Pune Railway Station", "Shivajinagar", "Khadki"] },
  { id: "t10", source: "khad", destination: "prs", mode: "Train", distance: 6.0, time: 12, fare: 8, routeNumber: "Local", stops: ["Khadki", "Shivajinagar", "Pune Railway Station"] },

  // Taxi / Cab (higher fare, faster)
  { id: "x1", source: "prs", destination: "vitp", mode: "Taxi", distance: 12.0, time: 30, fare: 250, routeNumber: "Cab", stops: [] },
  { id: "x2", source: "vitp", destination: "prs", mode: "Taxi", distance: 12.0, time: 30, fare: 250, routeNumber: "Cab", stops: [] },
  { id: "x3", source: "prs", destination: "airp", mode: "Taxi", distance: 14.0, time: 35, fare: 300, routeNumber: "Cab", stops: [] },
  { id: "x4", source: "airp", destination: "prs", mode: "Taxi", distance: 14.0, time: 35, fare: 300, routeNumber: "Cab", stops: [] },
  { id: "x5", source: "hinj", destination: "prs", mode: "Taxi", distance: 18.0, time: 45, fare: 350, routeNumber: "Cab", stops: [] },
  { id: "x6", source: "prs", destination: "hinj", mode: "Taxi", distance: 18.0, time: 45, fare: 350, routeNumber: "Cab", stops: [] },
  { id: "x7", source: "swar", destination: "vitp", mode: "Taxi", distance: 8.0, time: 20, fare: 180, routeNumber: "Cab", stops: [] },
  { id: "x8", source: "vitp", destination: "swar", mode: "Taxi", distance: 8.0, time: 20, fare: 180, routeNumber: "Cab", stops: [] },

  // Walking (short distances)
  { id: "w1", source: "prs", destination: "camp", mode: "Walking", distance: 1.2, time: 15, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w2", source: "camp", destination: "prs", mode: "Walking", distance: 1.2, time: 15, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w3", source: "shiv", destination: "fcro", mode: "Walking", distance: 0.8, time: 10, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w4", source: "fcro", destination: "shiv", mode: "Walking", distance: 0.8, time: 10, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w5", source: "decc", destination: "jmro", mode: "Walking", distance: 0.5, time: 7, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w6", source: "jmro", destination: "decc", mode: "Walking", distance: 0.5, time: 7, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w7", source: "civi", destination: "samb", mode: "Walking", distance: 0.6, time: 8, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "w8", source: "samb", destination: "civi", mode: "Walking", distance: 0.6, time: 8, fare: 0, routeNumber: "Walk", stops: [] },

  // Additional useful links
  { id: "c51", source: "shiv", destination: "decc", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMT-22", stops: ["Shivajinagar", "Deccan"] },
  { id: "c52", source: "decc", destination: "shiv", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMT-22", stops: ["Deccan", "Shivajinagar"] },
  { id: "c53", source: "koth", destination: "vana", mode: "Bus", distance: 2.0, time: 8, fare: 10, routeNumber: "PMT-K2", stops: ["Kothrud", "Vanaz"] },
  { id: "c54", source: "vana", destination: "koth", mode: "Bus", distance: 2.0, time: 8, fare: 10, routeNumber: "PMT-K2", stops: ["Vanaz", "Kothrud"] },
  { id: "c55", source: "bane", destination: "aund", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-BA", stops: ["Baner", "Aundh"] },
  { id: "c56", source: "aund", destination: "bane", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-BA", stops: ["Aundh", "Baner"] },
  { id: "c57", source: "dapo", destination: "pcmc", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMPML-D", stops: ["Dapodi", "PCMC"] },
  { id: "c58", source: "pcmc", destination: "dapo", mode: "Bus", distance: 4.0, time: 15, fare: 12, routeNumber: "PMPML-D", stops: ["PCMC", "Dapodi"] },
  { id: "c59", source: "bhos", destination: "pcmc", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMPML-B", stops: ["Bhosari", "PCMC"] },
  { id: "c60", source: "pcmc", destination: "bhos", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMPML-B", stops: ["PCMC", "Bhosari"] },
  { id: "c61", source: "sinh", destination: "katr", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-S1", stops: ["Sinhagad Road", "Katraj"] },
  { id: "c62", source: "katr", destination: "sinh", mode: "Bus", distance: 3.5, time: 12, fare: 12, routeNumber: "PMT-S1", stops: ["Katraj", "Sinhagad Road"] },
  { id: "c63", source: "maga", destination: "hada", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMT-M1", stops: ["Magarpatta", "Hadapsar"] },
  { id: "c64", source: "hada", destination: "maga", mode: "Bus", distance: 2.5, time: 10, fare: 10, routeNumber: "PMT-M1", stops: ["Hadapsar", "Magarpatta"] },
  { id: "c65", source: "phoe", destination: "vima", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-PH", stops: ["Phoenix Mall", "Viman Nagar"] },
  { id: "c66", source: "vima", destination: "phoe", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-PH", stops: ["Viman Nagar", "Phoenix Mall"] },
  { id: "c67", source: "kore", destination: "bund", mode: "Bus", distance: 2.0, time: 8, fare: 10, routeNumber: "PMT-KP", stops: ["Koregaon Park", "Bund Garden"] },
  { id: "c68", source: "bund", destination: "kore", mode: "Bus", distance: 2.0, time: 8, fare: 10, routeNumber: "PMT-KP", stops: ["Bund Garden", "Koregaon Park"] },
  { id: "c69", source: "puneuni", destination: "aund", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-U1", stops: ["Pune University", "Aundh"] },
  { id: "c70", source: "aund", destination: "puneuni", mode: "Bus", distance: 3.0, time: 12, fare: 12, routeNumber: "PMT-U1", stops: ["Aundh", "Pune University"] },
  { id: "c71", source: "bavd", destination: "koth", mode: "Bus", distance: 4.0, time: 15, fare: 15, routeNumber: "PMT-BV", stops: ["Bavdhan", "Kothrud"] },
  { id: "c72", source: "koth", destination: "bavd", mode: "Bus", distance: 4.0, time: 15, fare: 15, routeNumber: "PMT-BV", stops: ["Kothrud", "Bavdhan"] },
  { id: "c73", source: "sus", destination: "bane", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-SU", stops: ["Sus", "Baner"] },
  { id: "c74", source: "bane", destination: "sus", mode: "Bus", distance: 5.0, time: 18, fare: 15, routeNumber: "PMT-SU", stops: ["Baner", "Sus"] },
  // More metro connectivity
  { id: "m29", source: "vana", destination: "koth", mode: "Walking", distance: 1.5, time: 18, fare: 0, routeNumber: "Walk", stops: [] },
  { id: "m30", source: "koth", destination: "vana", mode: "Walking", distance: 1.5, time: 18, fare: 0, routeNumber: "Walk", stops: [] }
];

// Mode icons and colors
const MODE_INFO = {
  Bus: { icon: "🚌", color: "#2563eb", label: "Bus" },
  Metro: { icon: "🚇", color: "#7c3aed", label: "Metro" },
  Auto: { icon: "🛺", color: "#f59e0b", label: "Auto Rickshaw" },
  Train: { icon: "🚆", color: "#059669", label: "Local Train" },
  Taxi: { icon: "🚕", color: "#dc2626", label: "Taxi / Cab" },
  Walking: { icon: "🚶", color: "#6b7280", label: "Walking" },
  Bicycle: { icon: "🚲", color: "#10b981", label: "Bicycle" }
};

// Quick locations for home page
const QUICK_LOCATIONS = [
  "Pune Railway Station",
  "Swargate",
  "Shivajinagar",
  "VIT Pune",
  "PCMC",
  "Katraj",
  "Hinjawadi",
  "Pune Airport"
];
